server:
  port: 8080
spring:
  application:
    name: "ms-loan-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: "${R2DBC_HOST:localhost}"
    port: "${R2DBC_PORT:5432}"
    database: "${R2DBC_DATABASE:ms-loan}"
    username: "${R2DBC_USERNAME:postgres}"
    password: "${R2DBC_PASSWORD:S3cureP@ssw0rd!}"
    schema: "${R2DBC_SCHEMA:public}"